language: php

dist: focal

matrix:
  fast_finish: true
  include:
    - php: 7.4
    - php: 8.0
    - php: 8.1
    - php: 8.2
    - php: 8.3.0

sudo: false

install: travis_retry composer install

script: composer ci

notifications:
  irc:
    channels:
      - "irc.libera.chat#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

cache:
  directories:
    - $HOME/.composer/cache
