language: php

php:
  - 5.5
  - 5.6
  - 7
  - hhvm

sudo: false

install: travis_retry composer install

script: composer ci

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikidata-feed"
    on_success: change
    on_failure: always
    template:
      - "%{repository}/%{branch}/%{commit} : %{author} %{message} %{build_url}"

cache:
  directories:
    - $HOME/.composer/cache
